name: Gocheerio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        
    - name: Get dependencies
      run: go mod download
      
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-${{ matrix.go-version }}
        path: |
          ./*
        retention-days: 5