name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-lint:
    name: Tests and Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2
          export PATH=$(go env GOPATH)/bin:$PATH

      - name: Run Tests
        run: |
          go test ./... -v

      - name: Run Linter
        run: |
          golangci-lint run
        env:
          GOLANGCI_LINT_VERSION: "v1.62.2"
